import { defineConfig, loadEnv } from "vite";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import react from "@vitejs/plugin-react";
import basicSsl from '@vitejs/plugin-basic-ssl'
import { VitePWA } from "vite-plugin-pwa";

import { cloudflare } from "@cloudflare/vite-plugin";

/** Minimal KEY=VALUE parser (quotes + # comments) for .env.example fallback. */
function parseEnvFile(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if (
      (val.startsWith("'") && val.endsWith("'")) ||
      (val.startsWith('"') && val.endsWith('"'))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

/**
 * Cloudflare's git build checks out the repo without the git-ignored `.env`, so
 * every `import.meta.env.VITE_*` would otherwise bake in empty and the deployed
 * app loses its KV URL / HTLC address / chain id. Fall back to `.env.example`
 * for any VITE_ var not already provided — a real `.env` file or an explicit
 * CI/dashboard env var always takes precedence (we only fill what's unset).
 */
function applyExampleEnvFallback(mode: string): void {
  const loaded = loadEnv(mode, process.cwd(), "");
  const examplePath = resolve(process.cwd(), ".env.example");
  if (!existsSync(examplePath)) return;
  const example = parseEnvFile(readFileSync(examplePath, "utf8"));
  for (const [key, value] of Object.entries(example)) {
    if (key.startsWith("VITE_") && !loaded[key]) process.env[key] = value;
  }
}

/** One dev-proxy entry per RPC preset: `/__rpc/<id>/…` → the upstream host. Lets
 * both endpoints work locally regardless of their CORS policy. Keep in sync with
 * RPC_PRESETS in src/rpc/client.ts. */
const RPC_UPSTREAMS: Record<string, string> = {
  nockbox: "https://rpc.nockbox.org",
  nockchain: "https://rpc.nockchain.net",
};

function rpcProxy() {
  const proxy: Record<string, object> = {};
  for (const [id, target] of Object.entries(RPC_UPSTREAMS)) {
    const host = new URL(target).host;
    proxy[`/__rpc/${id}`] = {
      target,
      changeOrigin: true,
      secure: true,
      rewrite: (p: string) => p.replace(new RegExp(`^/__rpc/${id}`), ""),
      configure: (instance: { on: (e: string, cb: (req: { setHeader: (k: string, v: string) => void }) => void) => void }) => {
        instance.on("proxyReq", (req) => {
          req.setHeader("origin", `https://${host}`);
          req.setHeader("referer", `https://${host}/`);
        });
      },
    };
  }
  return proxy;
}

export default defineConfig(({ mode }) => {
  applyExampleEnvFallback(mode);
  return {
    server: {
      port: 5173,
      proxy: rpcProxy(),
    },
    // rose-ts is symlinked (file: dep) and ships its own node_modules; dedupe the
    // shared crypto libs so the symlink boundary resolves a single copy (avoids
    // mixed @noble/hashes versions across rose-web and rose-ts).
    resolve: {
      // Keep @noble/hashes out of dedupe: rose-ts needs v2, viem needs v1 subpath exports.
      // Also keep @scure/bip39 out: rose-web + rose-ts use v2 (whose wordlist
      // subpath is `./wordlists/english.js`), but the WalletConnect/ox tree pulls
      // v1 and imports the bare `./wordlists/english` — deduping would force those
      // v1 consumers onto v2 and break resolution. Both versions coexist fine
      // (bip39 is pure, deterministic, no shared mutable state).
      dedupe: ["@scure/base", "react", "react-dom"],
    },
    plugins: [basicSsl(), react(), VitePWA({
      registerType: "autoUpdate",
      injectRegister: "auto",
      // Generated by @vite-pwa/assets-generator from public/app-icon.png.
      includeAssets: ["apple-touch-icon-180x180.png", "favicon.ico"],
      manifest: {
        name: "Nock Wallet",
        short_name: "Nock",
        description: "A non-custodial Nockchain web wallet powered by rose-ts.",
        // Match the app's dark theme (src/style.css --bg) so the standalone
        // window and Android status bar blend with the UI.
        theme_color: "#0e0f13",
        background_color: "#0e0f13",
        display: "standalone",
        orientation: "portrait",
        start_url: "/",
        scope: "/",
        icons: [
          { src: "pwa-192x192.png", sizes: "192x192", type: "image/png" },
          { src: "pwa-512x512.png", sizes: "512x512", type: "image/png" },
          {
            src: "maskable-icon-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
      },
      workbox: {
        // Precache the app shell (Vite's hashed build assets) and fall back to
        // index.html for SPA routes (/connect, /swap/:id, …) when offline.
        // Cross-origin traffic (RPC, swap KV, price feed, WalletConnect relay)
        // is left untouched — Workbox ignores cross-origin + non-GET by default,
        // and we deliberately add no runtime caching for it.
        navigateFallback: "index.html",
        globPatterns: ["**/*.{js,css,html,svg,png,ico,woff2}"],
      },
      // Keep the service worker out of `npm run dev`; basicSsl() already serves
      // dev over HTTPS, and an active SW makes hot-reload debugging painful.
      devOptions: { enabled: false },
    }), cloudflare()],
  };
});